import {
    ChevronDown,
    ChevronRight,
    GraduationCap,
  } from "lucide-react";
  
  export default function DesktopLearningHub({
    item,
    active,
    onItemClick,
  }) {
    return (
      <div
        className="
          group/dropdown
          relative
        "
      >
        <button
          type="button"
          className={`
            group
            flex
            min-w-[92px]
            cursor-pointer
            flex-col
            items-center
            justify-center
            gap-1
            rounded-[16px]
            px-3
            py-2
            transition-all
            duration-300
            xl:min-w-[105px]
  
            ${
              active
                ? `
                    bg-gradient-to-br
                    from-[#edf8ff]
                    to-[#cfefff]
                    text-[#164fa5]
                    shadow-[0_8px_20px_rgba(1,124,192,0.10)]
                  `
                : `
                    text-[#07194f]
                    hover:bg-[#f2f8ff]
                    hover:text-[#017cc0]
                  `
            }
          `}
        >
          <span
            className="
              flex
              h-7
              items-center
              justify-center
              gap-1
              text-[18px]
            "
          >
            {item.icon}
  
            <ChevronDown
              className="
                h-3
                w-3
                transition-transform
                duration-300
                group-hover/dropdown:rotate-180
              "
            />
          </span>
  
          <span
            className="
              whitespace-nowrap
              text-[11px]
              font-semibold
              xl:text-[12px]
            "
          >
            {item.label}
          </span>
        </button>
  
        <div
          className="
            invisible
            absolute
            left-1/2
            top-[calc(100%+8px)]
            w-[620px]
            -translate-x-1/2
            translate-y-2
            opacity-0
            transition-all
            duration-200
            group-hover/dropdown:visible
            group-hover/dropdown:translate-y-0
            group-hover/dropdown:opacity-100
          "
        >
          <div
            className="
              absolute
              -top-3
              left-0
              h-4
              w-full
            "
          />
  
          <div
            className="
              overflow-hidden
              rounded-[22px]
              border
              border-[#dceafa]
              bg-white
              p-3
              shadow-[0_24px_60px_rgba(8,31,92,0.16)]
            "
          >
            <div
              className="
                mb-2
                flex
                items-center
                gap-3
                rounded-[15px]
                bg-gradient-to-r
                from-[#edf8ff]
                to-[#f5f0ff]
                px-4
                py-3
              "
            >
              <div
                className="
                  flex
                  h-10
                  w-10
                  items-center
                  justify-center
                  rounded-xl
                  bg-[#075ee7]
                  text-white
                "
              >
                <GraduationCap
                  size={20}
                />
              </div>
  
              <div>
                <p
                  className="
                    text-sm
                    font-black
                    text-[#082b7a]
                  "
                >
                  Learning Hub
                </p>
  
                <p
                  className="
                    text-[11px]
                    text-[#7085a8]
                  "
                >
                  Everything you
                  need for smarter
                  preparation.
                </p>
              </div>
            </div>
  
            <div
              className="
                grid
                grid-cols-2
                gap-1
              "
            >
              {item.children.map(
                (child) => (
                  <button
                    key={
                      child.title
                    }
                    type="button"
                    onClick={() =>
                      onItemClick(
                        child
                      )
                    }
                    className="
                      group/item
                      flex
                      w-full
                      cursor-pointer
                      items-center
                      gap-3
                      rounded-[14px]
                      px-3
                      py-3
                      text-left
                      transition-all
                      duration-200
                      hover:bg-[#f4f9ff]
                    "
                  >
                    <span
                      className="
                        flex
                        h-10
                        w-10
                        shrink-0
                        items-center
                        justify-center
                        rounded-xl
                        bg-[#edf6ff]
                        text-lg
                      "
                    >
                      {child.icon}
                    </span>
  
                    <div
                      className="
                        min-w-0
                        flex-1
                      "
                    >
                      <p
                        className="
                          text-[12px]
                          font-bold
                          text-[#102f68]
                        "
                      >
                        {
                          child.title
                        }
                      </p>
  
                      <p
                        className="
                          mt-0.5
                          truncate
                          text-[10px]
                          text-[#7b8daa]
                        "
                      >
                        {
                          child.subtitle
                        }
                      </p>
                    </div>
  
                    <ChevronRight
                      className="
                        h-3.5
                        w-3.5
                        shrink-0
                        text-[#9badc5]
                        transition-all
                        group-hover/item:translate-x-0.5
                        group-hover/item:text-[#087ee9]
                      "
                    />
                  </button>
                )
              )}
            </div>
          </div>
        </div>
      </div>
    );
  }